/* Automatically generated by './build/build-entry.js' */
/* Do not modify this file manually */

import Alert from './alert/index.js'
import Avatar from './avatar/index.js'
import ByteSize from './byte-size/index.js'
import Button from './button/index.js'
import Card from './card/index.js'
import Cell from './cell/index.js'
import CellGroup from './cell-group/index.js'
import Circle from './circle/index.js'
import Clipboard from './clipboard/index.js'
import Clock from './clock/index.js'
import ColorBlock from './color-block/index.js'
import CountDown from './count-down/index.js'
import Coupon from './coupon/index.js'
import Currency from './currency/index.js'
import Descriptions from './descriptions/index.js'
import DescriptionsItem from './descriptions-item/index.js'
import Device from './device/index.js'
import Field from './field/index.js'
import GoodsAction from './goods-action/index.js'
import GoodsActionButton from './goods-action-button/index.js'
import GoodsActionIcon from './goods-action-icon/index.js'
import GoodsBlock from './goods-block/index.js'
import GoodsCard from './goods-card/index.js'
import Grid from './grid/index.js'
import GridItem from './grid-item/index.js'
import Icon from './icon/index.js'
import Image from './image/index.js'
import Lazyload from './lazyload/index.js'
import NavBar from './nav-bar/index.js'
import NoticeBar from './notice-bar/index.js'
import Overlay from './overlay/index.js'
import Phone from './phone/index.js'
import PhoneNumber from './phone-number/index.js'
import PlaceHolder from './place-holder/index.js'
import Progress from './progress/index.js'
import RatioBox from './ratio-box/index.js'
import RemoteScript from './remote-script/index.js'
import ScaleBox from './scale-box/index.js'
import Search from './search/index.js'
import Statistic from './statistic/index.js'
import Sticky from './sticky/index.js'
import Swipe from './swipe/index.js'
import SwipeCell from './swipe-cell/index.js'
import SwipeItem from './swipe-item/index.js'
import Tab from './tab/index.js'
import Tabbar from './tabbar/index.js'
import TabbarItem from './tabbar-item/index.js'
import Tabs from './tabs/index.js'
import Tag from './tag/index.js'
import ZoomBox from './zoom-box/index.js'

import './style/index.scss'

const version = '2.0.6'

const components = [
  Alert,
  Avatar,
  ByteSize,
  Button,
  Card,
  Cell,
  CellGroup,
  Circle,
  Clipboard,
  Clock,
  ColorBlock,
  CountDown,
  Coupon,
  Currency,
  Descriptions,
  DescriptionsItem,
  Device,
  Field,
  GoodsAction,
  GoodsActionButton,
  GoodsActionIcon,
  GoodsBlock,
  GoodsCard,
  Grid,
  GridItem,
  Icon,
  Image,
  Lazyload,
  NavBar,
  NoticeBar,
  Overlay,
  Phone,
  PhoneNumber,
  PlaceHolder,
  Progress,
  RatioBox,
  RemoteScript,
  ScaleBox,
  Search,
  Statistic,
  Sticky,
  Swipe,
  SwipeCell,
  SwipeItem,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Tag,
  ZoomBox
]

const install = function (Vue) {
  components.forEach(component => {
    if (component && component.install) {
      Vue.use(component)
    } else if (component && component.name) {
      Vue.component(component.name, component)
    }
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export {
  install,
  version,
  Alert,
  Avatar,
  ByteSize,
  Button,
  Card,
  Cell,
  CellGroup,
  Circle,
  Clipboard,
  Clock,
  ColorBlock,
  CountDown,
  Coupon,
  Currency,
  Descriptions,
  DescriptionsItem,
  Device,
  Field,
  GoodsAction,
  GoodsActionButton,
  GoodsActionIcon,
  GoodsBlock,
  GoodsCard,
  Grid,
  GridItem,
  Icon,
  Image,
  Lazyload,
  NavBar,
  NoticeBar,
  Overlay,
  Phone,
  PhoneNumber,
  PlaceHolder,
  Progress,
  RatioBox,
  RemoteScript,
  ScaleBox,
  Search,
  Statistic,
  Sticky,
  Swipe,
  SwipeCell,
  SwipeItem,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Tag,
  ZoomBox
}

export default {
  version,
  install
}
